#1.配置服务器连接数据库接口

server:
  port: 8080
  servlet:
      context-path: "/"

#2. 对于数据源的配置


spring:
  datasource:
    name: evaluate
    url: jdbc:mysql://localhost:3306/evaluate
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    mvc:
      static-path-pattern: classpath:/static/**
      thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
      jackson:
      date-format: 'yyyy-MM-dd HH:mm:ss'
      joda-date-time-format: 'yyyy-MM-dd HH:mm:ss'
      time-zone: GMT+8
  resources:
    static-locations: classpath:/static/

#3.mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
